### PR TITLE
Added bootloader test and removed old files

### PR DESCRIPTION
**Pull request by lost-hope**
As we talked about it: 
removing 0.13.1 release and the 0.14.1 beta files
and added a radio button entry for a bootloader test (can be reused later for other public tests)

### CODE REVIEW

**Comment by lost-hope** [comment]
Corrected accordingly. 
(though i have to learn how to properly revert ^^)

**Comment by blazoncek** [comment]
Undo commit, re-commit and force push.
IMO a bad practice.

**Comment by lost-hope** [comment]
did it. i get why it is a bad practice. the "real" history gets removed.

**Comment by blazoncek** [comment]
and if I was working on your commit then I have a problem and will need to resolve the issue the hard way

**Pull request merged**
